# Server Configuration
server:
  port: ${PORT:8080}

# Management settings for health and metrics endpoints
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health'
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

# Database Configuration
spring:
  datasource:
    url: ${INTERNAL_DATABASE_URL:jdbc:postgresql://localhost:5432/fhir_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
  main:
    lazy-initialization: true
  flyway:
    enabled: false

# HAPI FHIR settings
hapi:
  fhir:
    version: R4
    allow_external_references: true
    allow_multiple_delete: true
    reuse_cached_search_results_millis: 60000
    retain_cached_searches_mins: 10
    cr_enabled: false