# Server Configuration
server:
  port: ${PORT:8080}

# Database Configuration
spring:
  datasource:
    url: ${INTERNAL_DATABASE_URL:jdbc:postgresql://localhost:5432/fhir_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 10
        generate_statistics: false
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  flyway:
    enabled: false

# HAPI FHIR settings
hapi:
  fhir:
    fhir_version: ${HAPI_FHIR_VERSION:R4}
    allow_external_references: true
    allow_multiple_delete: true
    cr_enabled: false
    validation:
      enabled: false
    jpa:
      defer_indexing_for_codesystems_of_size: 101
      auto_create_placeholder_references: true