# Server Configuration
server:
  port: 8080

# Management settings for health and metrics endpoints
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health'
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

# Database Configuration (adjust this as needed)
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: false
      format_sql: false
      dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
  main:
    lazy-initialization: true
  flyway:
    enabled: false

# HAPI FHIR settings
hapi:
  fhir:
    version: R4
    allow_external_references: true
    allow_multiple_delete: true
    reuse_cached_search_results_millis: 60000
    retain_cached_searches_mins: 10