# Server Configuration
server:
  port: ${PORT:8080}

# Database Configuration
spring:
  datasource:
    url: jdbc:${INTERNAL_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  flyway:
    enabled: false

# HAPI FHIR settings
hapi:
  fhir:
    fhir_version: ${HAPI_FHIR_VERSION:R4}
    cr_enabled: ${HAPI_FHIR_CR_ENABLED:false}
    allow_external_references: true
    allow_multiple_delete: true
    reuse_cached_search_results_millis: 60000
    retain_cached_searches_mins: 10
    validation:
      enabled: false
    jpa:
      defer_indexing_for_codesystems_of_size: 101
      auto_create_placeholder_references: true